// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace maritz_app.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630230848_AddPointsTransaction")]
    partial class AddPointsTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("maritz_app.Server.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Sales",
                            Name = "Ana Reyes",
                            Points = 120
                        },
                        new
                        {
                            Id = 2,
                            Department = "Service",
                            Name = "Marcus Lee",
                            Points = 80
                        },
                        new
                        {
                            Id = 3,
                            Department = "Marketing",
                            Name = "Priya Shah",
                            Points = 200
                        },
                        new
                        {
                            Id = 4,
                            Department = "Engineering",
                            Name = "Kevin Dizon",
                            Points = 150
                        },
                        new
                        {
                            Id = 5,
                            Department = "Human Resources",
                            Name = "Matthew Garcia",
                            Points = 90
                        });
                });

            modelBuilder.Entity("maritz_app.Server.PointsTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PointsTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
